### ISSUE TITLE
Error initializing application storage

### ISSUE THREAD

**Issue by SpiritAxolotl** [cpsdqs/prechoster#13]
Chrome 116.0, MacOS Ventura, M1 Macbook Pro

Running it on the deployed version or locally doesn't work. 

I've narrowed down the error to be line 8 of `src/storage/index.ts`. Was gonna try fix it myself but im scared of react.

Here's more info:
![Screenshot 2024-05-05 at 7 10 49 PM](https://github.com/cpsdqs/prechoster/assets/83354374/b553053a-0c61-4970-92bf-5c96db83afe0)

![Screenshot 2024-05-05 at 7 10 12 PM](https://github.com/cpsdqs/prechoster/assets/83354374/2c0a1b74-705c-41de-956b-85cc2652f6bb")

**Comment by c-probably-archived20260718** [comment]
“Internal error” seems to be pretty strong indication that this is a problem in the Chrome browser. Unfortunately there’s not really anything I can do here, I think? Maybe consider updating to a newer version, as it seems to be working fine for me on Chromium 124

**Comment by SpiritAxolotl** [comment]
kinda stuck on chromium 116 so I'll survive for the time being by just using safari.

**Comment by c-probably-archived20260718** [comment]
i thought about it and there was something i could do actually. it will now work fine except the whole storage part which will simply not

**Comment by SpiritAxolotl** [comment]
oh swag
