### ISSUE TITLE
Error: Error in svelte worker

### ISSUE THREAD

**Issue by mruac** [cpsdqs/prechoster#15]
Thought it was my previously working template was the issue, but this is impacting the examples that use svelte as well.

When opening the request for `https://cloudwithlightning.net/random/chostin/prechoster/assets/svelte-worker-d7751f82.js` in a new tab, it could only respond with this instead of the usual JS stuff.
```
d
```

**Comment by c-probably-archived20260718** [comment]
That’s not supposed to happen… and I also don’t know how this could happen… have you tried force-reloading the page, or just opening it in a private browsing window? It might just be a bad cache

**Comment by mruac** [comment]
Must be - it seems to have resolved itself on the desktop but not yet on my phone.
