### ISSUE TITLE
Should warn when using tags Cohost doesn't allow.

### ISSUE THREAD

**Issue by remeranAuthor** [cpsdqs/prechoster#2]
Cohost doesn't allow any tags that aren't on their white list, which doesn't include things like \<article\> or the like. The linter should yell at me not to use those. It leads to the preview prechoster provides not matching what gets posted to cohost. Warnings, or the option to replace things like article with div would be nice.

**Comment by c-probably-archived20260718** [comment]
yeah, there's actually a lot of rendering bits missing in the preview (e.g. :eggbug:). i tried removing some major disallowed tags like script and style, but there's not really a list of allowed or disallowed tags anywhere, and the minified client js is very difficult to read. if staff were to publish such a list or if anyone can find one, this should be easy to add though
