### ISSUE TITLE
what code formatter do you use?

### ISSUE THREAD

**Issue by easrng** [cpsdqs/prechoster#3]
Hi! I'm working on some changes to prechoster (making the markdown renderer more accurate to what cohost does) and I want to make sure they match the formatting (indentation, trailing commas, semicolon placement, etc) you already have but I can't just run prettier on everything because its defaults are different from what you used.

**Comment by c-probably-archived20260718** [comment]
hm! I didn’t use any formatter, that’s just how i write javascript. i’ve never used a javascript formatter before… i suppose i can try adding prettier
